import { Theme } from '../types';

export const themes: Record<string, Theme> = {
    default: {
        name: 'default',
        displayName: 'Default',
        colors: {
            primary: '#fc4c02',
            secondary: '#0066cc',
            background: '#ffffff',
            surface: '#f5f5f5',
            text: '#1a1a1a',
            textSecondary: '#666666',
            border: '#e0e0e0',
            accent: '#fc4c02',
        },
        map: {
            style: 'mapbox://styles/mapbox/streets-v12',
            routeColor: '#fc4c02',
            routeWidth: 4,
            routeOpacity: 0.8,
        },
        print: {
            pageBg: '#1a1a1a',
            footerText: '#ffffff',
            footerTextMuted: '#999999',
            printStyleUrl: 'mapbox://styles/mapbox/light-v11',
            accentRule: '#fc4c02',
            routeStrokeColor: 'fc4c02',
            routeStrokeWidth: 4,
        },
    },
    dark: {
        name: 'dark',
        displayName: 'Dark',
        colors: {
            primary: '#fc4c02',
            secondary: '#4da6ff',
            background: '#121212',
            surface: '#1e1e1e',
            text: '#ffffff',
            textSecondary: '#b3b3b3',
            border: '#333333',
            accent: '#fc4c02',
        },
        map: {
            style: 'mapbox://styles/mapbox/dark-v11',
            routeColor: '#fc4c02',
            routeWidth: 4,
            routeOpacity: 0.9,
        },
        print: {
            pageBg: '#12122a',
            footerText: '#ffffff',
            footerTextMuted: '#aaaacc',
            accentRule: '#fc4c02',
            routeStrokeColor: 'fc4c02',
            routeStrokeWidth: 4,
            printStyleUrl: 'mapbox://styles/mapbox/dark-v11',
        },
    },
    // themes.ts
    blueprint: {
        name: 'blueprint',
        displayName: 'Blueprint',
        colors: {
            primary: '#4da6ff',
            secondary: '#a8d4ff',
            background: '#0d1b2e',
            surface: '#112640',
            text: '#ffffff',
            textSecondary: '#a8d4ff',
            border: '#1a4a7a',
            accent: '#4da6ff',
        },
        map: {
            style: 'mapbox://styles/mapbox/dark-v11',
            routeColor: '#ffffff',
            routeWidth: 4,
            routeOpacity: 1,
        },
        print: {
            pageBg: '#0a1628',
            footerText: '#ffffff',
            footerTextMuted: '#4da6ff',
            accentRule: '#4da6ff',
            routeStrokeColor: 'ffffff',
            routeStrokeWidth: 4,
            printStyleUrl: 'mapbox://styles/atibhav21/blueprint',
        },
    },
    // themes.ts
    noir: {
        name: 'noir',
        displayName: 'Noir',
        colors: {
            primary: '#ffffff',
            secondary: '#aaaaaa',
            background: '#0d0d0d',
            surface: '#1a1a1a',
            text: '#ffffff',
            textSecondary: '#888888',
            border: '#2a2a2a',
            accent: '#ffffff',
        },
        map: {
            style: 'mapbox://styles/mapbox/dark-v11',
            routeColor: '#ffffff',
            routeWidth: 4,
            routeOpacity: 1,
        },
        print: {
            pageBg: '#0d0d0d',
            footerText: '#ffffff',
            footerTextMuted: '#666666',
            accentRule: '#ffffff',
            routeStrokeColor: 'ffffff',
            routeStrokeWidth: 4,
            printStyleUrl: 'mapbox://styles/atibhav21/noir',
        },
    },
    // themes.ts
    neonTokyo: {
        name: 'neonTokyo',
        displayName: 'Neon Tokyo',
        colors: {
            primary: '#ff2d78',
            secondary: '#00f5d4',
            background: '#0a0a0f',
            surface: '#120a1e',
            text: '#ffffff',
            textSecondary: '#cc66ff',
            border: '#2d0a4e',
            accent: '#ff2d78',
        },
        map: {
            style: 'mapbox://styles/mapbox/dark-v11',
            routeColor: '#ff2d78',
            routeWidth: 4,
            routeOpacity: 1,
        },
        print: {
            pageBg: '#0a0a0f',
            footerText: '#ffffff',
            footerTextMuted: '#cc66ff',
            accentRule: '#ff2d78',
            routeStrokeColor: 'ff2d78',
            routeStrokeWidth: 4,
            printStyleUrl: 'mapbox://styles/atibhav21/cmnlaj9vn006901sl0x2zd2oj',
        },
    },
    forest: {
        name: 'forest',
        displayName: 'Forest',
        colors: {
            primary: '#2d6a4f',
            secondary: '#52b788',
            background: '#f1f8f4',
            surface: '#e8f3ed',
            text: '#1b4332',
            textSecondary: '#40916c',
            border: '#95d5b2',
            accent: '#2d6a4f',
        },
        map: {
            style: 'mapbox://styles/mapbox/outdoors-v12',
            routeColor: '#8b1a1a',
            routeWidth: 3,
            routeOpacity: 0.95,
        },
        print: {
            pageBg: '#d4c5a0',       // warm parchment — matches the poster
            footerText: '#1b2e1b',
            footerTextMuted: '#5a4a2a',
            accentRule: '#3d1a0a',   // dark brown silhouette
            printStyleUrl: 'mapbox://styles/atibhav21/cmnlb0sxh006a01sl6n5c14aq',
            routeStrokeColor: '8b1a1a',   // dark red like the poster
            routeStrokeWidth: 3,
        },
    },
};