import { Theme } from '../types';

export const themes: Record<string, Theme> = {
    default: {
        name: 'default',
        displayName: 'Default',
        colors: {
            primary: '#fc4c02',
            secondary: '#0066cc',
            background: '#ffffff',
            surface: '#f5f5f5',
            text: '#1a1a1a',
            textSecondary: '#666666',
            border: '#e0e0e0',
            accent: '#fc4c02',
        },
        map: {
            style: 'mapbox://styles/mapbox/streets-v12',
            routeColor: '#fc4c02',
            routeWidth: 4,
            routeOpacity: 0.8,
        },
    },
    dark: {
        name: 'dark',
        displayName: 'Dark',
        colors: {
            primary: '#fc4c02',
            secondary: '#4da6ff',
            background: '#121212',
            surface: '#1e1e1e',
            text: '#ffffff',
            textSecondary: '#b3b3b3',
            border: '#333333',
            accent: '#fc4c02',
        },
        map: {
            style: 'mapbox://styles/mapbox/dark-v11',
            routeColor: '#fc4c02',
            routeWidth: 4,
            routeOpacity: 0.9,
        },
    },
    ocean: {
        name: 'ocean',
        displayName: 'Ocean',
        colors: {
            primary: '#0077be',
            secondary: '#00b4d8',
            background: '#f0f8ff',
            surface: '#e6f4f9',
            text: '#003d5c',
            textSecondary: '#006494',
            border: '#90cdf4',
            accent: '#0077be',
        },
        map: {
            style: 'mapbox://styles/mapbox/light-v11',
            routeColor: '#0077be',
            routeWidth: 4,
            routeOpacity: 0.85,
        },
    },
    forest: {
        name: 'forest',
        displayName: 'Forest',
        colors: {
            primary: '#2d6a4f',
            secondary: '#52b788',
            background: '#f1f8f4',
            surface: '#e8f3ed',
            text: '#1b4332',
            textSecondary: '#40916c',
            border: '#95d5b2',
            accent: '#2d6a4f',
        },
        map: {
            style: 'mapbox://styles/mapbox/outdoors-v12',
            routeColor: '#2d6a4f',
            routeWidth: 4,
            routeOpacity: 0.85,
        },
    },
    sunset: {
        name: 'sunset',
        displayName: 'Sunset',
        colors: {
            primary: '#ff6b35',
            secondary: '#f7931e',
            background: '#fff9f5',
            surface: '#fff0e6',
            text: '#5c2e0f',
            textSecondary: '#8b4513',
            border: '#ffc599',
            accent: '#ff6b35',
        },
        map: {
            style: 'mapbox://styles/mapbox/satellite-streets-v12',
            routeColor: '#ff6b35',
            routeWidth: 5,
            routeOpacity: 0.9,
        },
    },
};